### ISSUE TITLE
Exception thrown when shallow == true

### ISSUE THREAD

**Issue by pfrazee** [holepunchto/hyperdrive#135]
Bug in line https://github.com/mafintosh/hyperdrive/blob/master/index.js#L233

```
TypeError: self.content._storage.data.add is not a function
    at /Users/paulfrazee/my/pauls-dat-api/node_modules/hyperdrive/index.js:233:36
    at call (/Users/paulfrazee/my/pauls-dat-api/node_modules/mutexify/index.js:6:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

**Comment by mafintosh** [comment]
Ah yeah. That option actually isn't supported. Just forgot to remove the code for it. There gonna be a "latest: true" instead.
